
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan 10 2026 17:05:54 IST (Jan 10 2026 11:35:54 UTC)

// Verification Directory fv/uar 

module uar(dOut, dReady, dError, clk, gl_reset, dIn);
  input clk, gl_reset, dIn;
  output [7:0] dOut;
  output dReady, dError;
  wire clk, gl_reset, dIn;
  wire [7:0] dOut;
  wire dReady, dError;
  wire [3:0] s_d_shift_reg;
  wire [8:0] cov_count_reg;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_44, n_45, n_46, n_54, n_55;
  wire running;
  dfnrq1 fla_dError_reg(.CP (clk), .D (n_45), .Q (dError));
  dfnrq1 fla_dReady_reg(.CP (clk), .D (n_46), .Q (dReady));
  nr02d1 g544__6260(.A1 (n_44), .A2 (n_21), .ZN (n_46));
  oan211d1 g545__4319(.A (n_44), .B (n_17), .C1 (n_20), .C2 (dIn), .ZN
       (n_45));
  nr03d1 g551__8428(.A1 (s_d_shift_reg[3]), .A2 (s_d_shift_reg[2]), .A3
       (s_d_shift_reg[0]), .ZN (n_44));
  dfnrn1 \s_d_shift_reg_reg[3] (.CP (clk), .D (n_42), .QN
       (s_d_shift_reg[3]));
  dfnrq1 \cov_count_reg_reg[7] (.CP (clk), .D (n_41), .Q
       (cov_count_reg[7]));
  dfnrq1 \cov_count_reg_reg[8] (.CP (clk), .D (n_40), .Q
       (cov_count_reg[8]));
  an02d1 g561__5526(.A1 (n_36), .A2 (s_d_shift_reg[2]), .Z (n_42));
  oan211d1 g534__6783(.A (running), .B (n_35), .C1 (n_38), .C2
       (cov_count_reg[7]), .ZN (n_41));
  oan211d1 g547__3680(.A (running), .B (n_32), .C1 (n_31), .C2
       (cov_count_reg[8]), .ZN (n_40));
  dfnrq1 \s_d_shift_reg_reg[2] (.CP (clk), .D (n_37), .Q
       (s_d_shift_reg[2]));
  dfnrq1 \cov_count_reg_reg[5] (.CP (clk), .D (n_34), .Q
       (cov_count_reg[5]));
  ora211d1 g538__1617(.A (n_38), .B (n_5), .C1 (n_33), .C2
       (cov_count_reg[6]), .Z (n_39));
  dfnrq1 \s_p_dOut_reg[0] (.CP (clk), .D (n_24), .Q (dOut[0]));
  dfnrq1 \s_p_dOut_reg[7] (.CP (clk), .D (n_29), .Q (dOut[7]));
  dfnrq1 \s_p_dOut_reg[6] (.CP (clk), .D (n_30), .Q (dOut[6]));
  dfnrq1 \s_p_dOut_reg[3] (.CP (clk), .D (n_25), .Q (dOut[3]));
  dfnrq1 \s_p_dOut_reg[5] (.CP (clk), .D (n_27), .Q (dOut[5]));
  an02d1 g577__2802(.A1 (n_36), .A2 (s_d_shift_reg[1]), .Z (n_37));
  nd02d1 g537__1705(.A1 (n_38), .A2 (cov_count_reg[7]), .ZN (n_35));
  dfnrq1 \s_p_dOut_reg[1] (.CP (clk), .D (n_23), .Q (dOut[1]));
  dfnrq1 \s_p_dOut_reg[4] (.CP (clk), .D (n_22), .Q (dOut[4]));
  dfnrq1 \s_p_dOut_reg[2] (.CP (clk), .D (n_26), .Q (dOut[2]));
  aoim211d1 g550__5122(.A (n_33), .B (running), .C1 (n_18), .C2
       (cov_count_reg[5]), .ZN (n_34));
  nd02d1 g553__8246(.A1 (n_31), .A2 (cov_count_reg[8]), .ZN (n_32));
  mx02d1 g569__7098(.I0 (dOut[6]), .I1 (dOut[7]), .S (n_28), .Z (n_30));
  mx02d1 g568__6131(.I0 (dOut[7]), .I1 (dIn), .S (n_28), .Z (n_29));
  mx02d1 g567__1881(.I0 (dOut[5]), .I1 (dOut[6]), .S (n_28), .Z (n_27));
  mx02d1 g572__5115(.I0 (dOut[2]), .I1 (dOut[3]), .S (n_28), .Z (n_26));
  nd02d1 g548__7482(.A1 (n_33), .A2 (cov_count_reg[6]), .ZN (n_38));
  mx02d1 g575__4733(.I0 (dOut[3]), .I1 (dOut[4]), .S (n_28), .Z (n_25));
  mx02d1 g574__6161(.I0 (dOut[0]), .I1 (dOut[1]), .S (n_28), .Z (n_24));
  mx02d1 g573__9315(.I0 (dOut[1]), .I1 (dOut[2]), .S (n_28), .Z (n_23));
  mx02d1 g576__9945(.I0 (dOut[4]), .I1 (dOut[5]), .S (n_28), .Z (n_22));
  dfnrq1 \s_d_shift_reg_reg[1] (.CP (clk), .D (n_16), .Q
       (s_d_shift_reg[1]));
  aoi22d1 g580__2883(.A1 (n_14), .A2 (dIn), .B1 (n_20), .B2 (dReady),
       .ZN (n_21));
  dfnrq1 \cov_count_reg_reg[3] (.CP (clk), .D (n_15), .Q
       (cov_count_reg[3]));
  aoi211d1 g562__2346(.A (n_18), .B (running), .C1 (n_10), .C2 (n_11),
       .ZN (n_19));
  nd04d1 g563__1666(.A1 (cov_count_reg[5]), .A2 (n_18), .A3
       (cov_count_reg[6]), .A4 (cov_count_reg[7]), .ZN (n_31));
  nd02d1 g584__7410(.A1 (n_20), .A2 (dError), .ZN (n_17));
  an02d1 g564__6417(.A1 (n_18), .A2 (cov_count_reg[5]), .Z (n_33));
  an02d1 g588__5477(.A1 (n_36), .A2 (s_d_shift_reg[0]), .Z (n_16));
  dfnrq1 \cov_count_reg_reg[2] (.CP (clk), .D (n_12), .Q
       (cov_count_reg[2]));
  oan211d1 g585__2398(.A (running), .B (n_9), .C1 (n_13), .C2
       (cov_count_reg[3]), .ZN (n_15));
  nr02d1 g587__6260(.A1 (n_13), .A2 (n_14), .ZN (n_28));
  oan211d1 g579__4319(.A (running), .B (n_4), .C1 (n_6), .C2
       (cov_count_reg[2]), .ZN (n_12));
  dfnrq1 \cov_count_reg_reg[1] (.CP (clk), .D (n_7), .Q
       (cov_count_reg[1]));
  dfnrq1 \s_d_shift_reg_reg[0] (.CP (clk), .D (n_8), .Q
       (s_d_shift_reg[0]));
  inv0d0 g590(.I (n_14), .ZN (n_20));
  nr02d1 g583__8428(.A1 (n_11), .A2 (n_10), .ZN (n_18));
  nr04d1 g593__5526(.A1 (n_0), .A2 (cov_count_reg[5]), .A3 (n_13), .A4
       (n_3), .ZN (n_14));
  nd02d1 g596__6783(.A1 (n_13), .A2 (cov_count_reg[3]), .ZN (n_9));
  an02d1 g597__3680(.A1 (n_36), .A2 (dIn), .Z (n_8));
  ora211d1 g591__1617(.A (n_6), .B (n_5), .C1 (cov_count_reg[0]), .C2
       (cov_count_reg[1]), .Z (n_7));
  nd03d1 g592__2802(.A1 (n_2), .A2 (cov_count_reg[3]), .A3
       (cov_count_reg[2]), .ZN (n_10));
  nd02d1 g589__1705(.A1 (n_6), .A2 (cov_count_reg[2]), .ZN (n_4));
  dfnrq1 \cov_count_reg_reg[0] (.CP (clk), .D (n_1), .Q
       (cov_count_reg[0]));
  or04d0 g599__5122(.A1 (cov_count_reg[4]), .A2 (cov_count_reg[7]), .A3
       (cov_count_reg[8]), .A4 (cov_count_reg[3]), .Z (n_3));
  nd03d1 g600__8246(.A1 (cov_count_reg[2]), .A2 (cov_count_reg[1]), .A3
       (cov_count_reg[0]), .ZN (n_13));
  inv0d0 g594(.I (n_6), .ZN (n_2));
  nr02d1 g601__7098(.A1 (gl_reset), .A2 (n_5), .ZN (n_36));
  nd02d1 g603__6131(.A1 (cov_count_reg[1]), .A2 (cov_count_reg[0]), .ZN
       (n_6));
  nr02d0 g602__1881(.A1 (running), .A2 (cov_count_reg[0]), .ZN (n_1));
  dfnrb1 con_running_reg(.CP (clk), .D (n_55), .Q (n_5), .QN (running));
  dfnrb1 \cov_count_reg_reg[6] (.CP (clk), .D (n_39), .Q
       (cov_count_reg[6]), .QN (n_0));
  dfnrb1 \cov_count_reg_reg[4] (.CP (clk), .D (n_19), .Q
       (cov_count_reg[4]), .QN (n_11));
  nr03d0 g637(.A1 (n_54), .A2 (gl_reset), .A3 (n_14), .ZN (n_55));
  an12d1 g3(.A1 (n_44), .A2 (running), .Z (n_54));
endmodule

