
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan 10 2026 13:02:03 IST (Jan 10 2026 07:32:03 UTC)

// Verification Directory fv/RamChip 

module RamChip(Address, Data, CS, WE, OE);
  input [0:0] Address;
  input CS, WE, OE;
  inout [0:0] Data;
  wire [0:0] Address;
  wire CS, WE, OE;
  wire [0:0] Data;
  wire [0:0] \Mem[0] ;
  wire [0:0] \Mem[1] ;
  wire n_0, n_1, n_2, n_3, n_4;
  lanhq1 \Mem_reg[0][0] (.E (n_1), .D (Data), .Q (\Mem[0] ));
  lanhq1 \Mem_reg[1][0] (.E (n_4), .D (Data), .Q (\Mem[1] ));
  invtd1 g4__2398(.EN (n_0), .I (n_3), .ZN (Data));
  nr03d0 g61__5107(.A1 (CS), .A2 (WE), .A3 (n_2), .ZN (n_4));
  aoi22d1 g64__6260(.A1 (\Mem[0] ), .A2 (n_2), .B1 (\Mem[1] ), .B2
       (Address), .ZN (n_3));
  nr03d0 g62__4319(.A1 (CS), .A2 (Address), .A3 (WE), .ZN (n_1));
  or02d0 g63__8428(.A1 (CS), .A2 (OE), .Z (n_0));
  inv0d0 g65(.I (Address), .ZN (n_2));
endmodule

