
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan  6 2026 20:12:24 IST (Jan  6 2026 14:42:24 UTC)

// Verification Directory fv/Shifter 

module Shifter(Clk, EN, WR, RD, SI, SO, Data);
  input Clk, EN, WR, RD, SI;
  output SO;
  inout [0:0] Data;
  wire Clk, EN, WR, RD, SI;
  wire SO;
  wire [0:0] Data;
  wire [0:0] Shift_reg;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  inv0d0 g49(.I (n_4), .ZN (n_5));
  aoi322d1 g50__2398(.A1 (Data), .A2 (n_1), .B1 (n_2), .B2 (SI), .C1
       (Shift_reg), .C2 (EN), .C3 (WR), .ZN (n_4));
  dfnrq1 SO_reg(.CP (Clk), .D (n_3), .Q (SO));
  aor22d1 g51__5107(.A1 (Shift_reg), .A2 (n_2), .B1 (SO), .B2 (EN), .Z
       (n_3));
  invtd1 g2__6260(.EN (RD), .I (n_0), .ZN (Data));
  nr02d1 g52__4319(.A1 (WR), .A2 (n_2), .ZN (n_1));
  inv0d0 g54(.I (EN), .ZN (n_2));
  dfnrb1 \Shift_reg_reg[0] (.CP (Clk), .D (n_5), .Q (Shift_reg), .QN
       (n_0));
endmodule

