
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Jan 13 2026 20:11:15 IST (Jan 13 2026 14:41:15 UTC)

// Verification Directory fv/async_up_counter 

module async_up_counter(clk, reset, count);
  input clk, reset;
  output [3:0] count;
  wire clk, reset;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4;
  inv0d0 g10(.I (reset), .ZN (n_4));
  dfcfb1 tf1_q_reg(.CDN (n_4), .CPN (count[0]), .D (n_3), .Q
       (count[1]), .QN (n_3));
  dfcfb1 tf0_q_reg(.CDN (n_4), .CPN (clk), .D (n_2), .Q (count[0]), .QN
       (n_2));
  dfcfb1 tf2_q_reg(.CDN (n_4), .CPN (count[1]), .D (n_1), .Q
       (count[2]), .QN (n_1));
  dfcfb1 tf3_q_reg(.CDN (n_4), .CPN (count[2]), .D (n_0), .Q
       (count[3]), .QN (n_0));
endmodule

